In [1]:
import pandas as pd
from constants import *
import os

In [2]:
def read_data(year, fname):
    df = pd.read_csv(fname, index_col=0)
    zev = df.loc["NONCARB", "Odds Ratio"]
    pov = df.loc["POVERTY", "Odds Ratio"]
    print(year, zev, pov)
    return df

In [4]:
for state_code in ZEV_STATES:
    years = list(range(2008, 2020))
    dir_path = "odds_ratio_module/data/{}/{}"
    print(state_code)
    for year in years:
        path = dir_path.format(year, "epa_region_0_CHILD_zev_{}.csv".format(state_code))
        if os.path.exists(path):
            read_data(year, path)

6
2008 1.1337439520444914 1.155299819906813
2009 1.1535136360078277 1.1143035495101907
2012 1.4687481553247372 1.2556238472768324
2013 1.720847717022694 1.3029910665416942
2014 1.552661151070679 1.2131312240504781
2015 1.4621965590033426 1.3839516441900075
2016 1.8038499467403344 1.0809108827295102
2017 1.23103129717867 1.5039872212761187
2018 1.36192776922019 1.0934832880499985
2019 1.6097460987067356 1.199048287614903
9
2008 1.0510277278033595 1.176194685365983
2009 1.102846881440799 1.143741941649437
2010 1.1737815869149877 1.2609271904380537
2011 1.306779682875761 1.3532993036205818
2012 1.001269040450842 1.2997097390573145
2013 0.9276860212303516 1.3732308022174835
2014 0.9164473963406232 1.2672567060286604
2015 1.1828930423931183 1.4200177077162983
2016 1.1683042017133844 1.1327552886891403
2017 1.5639238501724675 1.557121156817521
2018 1.1545912531935625 1.120865517111462
2019 0.9294624527520856 1.2521185652011926
23
2008 0.5439386514742689 1.1749841283055469
2016 0.5137648575406183 1.1309555538525842
2017 0.5931380758999596 1.558132386065462
2018 0.5285352058436216 1.1178373541687852
2019 0.7016812776762629 1.2522940104377676
24
2008 0.8055345344550772 1.1695314166120403
2009 1.0630984807902188 1.1443453189409716
2010 1.1708019299850776 1.2667739469822916
2012 0.8977402352593209 1.2971941415342392
2013 0.9596663914654666 1.3722912942406122
2014 0.9150599596126922 1.2662353956332315
25
34
2008 0.4088687812086765 1.1859111591309774
2009 0.3992691043083592 1.1437159949937112
2010 0.5181424878854066 1.2766263168878285
2011 0.5723689647958883 1.3536112308188095
2012 0.37960595206354464 1.298992932844944
2014 0.569516824693215 1.2691301924079366
2015 0.408089643191685 1.4138528404497333
2016 0.6107175853133214 1.1289845517003334
36
2008 1.5570500665675855 1.190960003333149
2009 1.4114207174526303 1.1503825569695465
2012 1.3289874005263047 1.2890540667968602
41
2008 0.5707537429700295 1.1746646703314214
2010 0.8096473296461992 1.257557893210127
2011 1.0707886334684946 1.3524695393532509
2012 0.7620149120992701 1.2986185033568023
2013 0.8668602213206742 1.3733530955987363
2014 0.742961216554185 1.2664475259202277
2015 1.0213314336730963 1.419351540309727
2016 0.5499382456817911 1.1329110077616409
2017 0.702564414253412 1.5574445487258235
2018 0.8925779721606053 1.1184555223071018
2019 0.9300112804494056 1.2524167093693879
44
2008 0.874320853209742 1.1757424998204655
2009 0.7690345612487222 1.1426597521267152
2010 0.9204541420952296 1.2597465442550506
2013 0.8286597288708418 1.3740783537290202
2014 0.7591062332579015 1.2680389046943314
2016 0.8532604443690852 1.1314654921703289
2017 0.8970584395833876 1.5595500052411209
2018 0.7578939690405652 1.1194501681630522
2019 0.6388329157140807 1.2516522287855152
50
2008 0.7558371725818521 1.1753401714625369
2009 0.7964778638975062 1.1423441040904412
2010 0.8291563645813965 1.2592003546671928
2013 0.8780666858161191 1.3737169302674994
2014 0.6764413830469502 1.2674247471589069
2015 0.8807906929673385 1.4189214264004533
2016 0.667404704300504 1.1311696182890685
2017 0.6980265112259592 1.5582067956780412
2018 0.8515981827646439 1.1188530300608992
2019 0.7815038538347178 1.2527027241231194

In [11]:
for state_code in ZEV_STATES:
    years = list(range(2008, 2020))
    dir_path = "odds_ratio_module/data/{}/{}"
    print(state_code)
    for year in years:
        path = dir_path.format(year, "epa_region_0_CHILD_zev_{}.csv".format(state_code))
        if os.path.exists(path):
            read_data(year, path)

6
2008 1.1337439520444914 1.155299819906813
2009 1.153513636007828 1.1143035495101907
2012 1.4687481553247372 1.2556238472768324
2013 1.720847717022694 1.302991066541694
2014 1.552661151070679 1.213131224050478
2015 1.4621965590033426 1.3839516441900075
2016 1.8038499467403344 1.0809108827295102
2017 1.23103129717867 1.5039872212761187
2018 1.36192776922019 1.0934832880499985
2019 1.6097460987067356 1.199048287614903
9
2008 1.0510277278033595 1.176194685365983
2009 1.102846881440799 1.143741941649437
2010 1.1737815869149877 1.2609271904380537
2011 1.306779682875761 1.353299303620582
2012 1.001269040450842 1.2997097390573145
2013 0.9276860212303516 1.3732308022174835
2014 0.9164473963406232 1.2672567060286604
2015 1.1828930423931183 1.4200177077162983
2016 1.1683042017133844 1.1327552886891403
2017 1.5639238501724675 1.557121156817521
2018 1.1545912531935625 1.120865517111462
2019 0.9294624527520856 1.2521185652011926
23
2008 0.5439386514742689 1.1749841283055469
2016 0.5137648575406183 1.1309555538525842
2017 0.5931380758999596 1.558132386065462
2018 0.5285352058436216 1.1178373541687852
2019 0.7016812776762629 1.2522940104377676
24
2008 0.8055345344550772 1.1695314166120403
2009 1.0630984807902188 1.1443453189409716
2010 1.1708019299850776 1.2667739469822916
2012 0.897740235259321 1.2971941415342392
2013 0.9596663914654666 1.3722912942406122
2014 0.9150599596126922 1.2662353956332315
25
34
2008 0.4088687812086765 1.1859111591309774
2009 0.3992691043083592 1.1437159949937112
2010 0.5181424878854066 1.2766263168878285
2011 0.5723689647958883 1.3536112308188095
2012 0.3796059520635446 1.298992932844944
2014 0.569516824693215 1.2691301924079366
2015 0.408089643191685 1.4138528404497333
2016 0.6107175853133214 1.1289845517003334
36
2008 1.5570500665675855 1.190960003333149
2009 1.4114207174526303 1.1503825569695465
2012 1.3289874005263047 1.28905406679686
41
2008 0.5707537429700295 1.1746646703314214
2010 0.8096473296461992 1.257557893210127
2011 1.0707886334684946 1.3524695393532509
2012 0.7620149120992701 1.2986185033568023
2013 0.8668602213206742 1.3733530955987363
2014 0.742961216554185 1.2664475259202277
2015 1.0213314336730963 1.419351540309727
2016 0.549938245681791 1.1329110077616409
2017 0.702564414253412 1.5574445487258235
2018 0.8925779721606053 1.1184555223071018
2019 0.9300112804494056 1.252416709369388
44
2008 0.874320853209742 1.1757424998204655
2009 0.7690345612487222 1.1426597521267152
2010 0.9204541420952296 1.2597465442550506
2013 0.8286597288708418 1.3740783537290202
2014 0.7591062332579015 1.2680389046943314
2016 0.8532604443690852 1.1314654921703289
2017 0.8970584395833876 1.559550005241121
2018 0.7578939690405652 1.1194501681630522
2019 0.6388329157140807 1.2516522287855152
50
2008 0.755837172581852 1.1753401714625369
2009 0.7964778638975062 1.1423441040904412
2010 0.8291563645813965 1.2592003546671928
2013 0.8780666858161191 1.3737169302674994
2014 0.6764413830469502 1.2674247471589069
2015 0.8807906929673385 1.4189214264004533
2016 0.667404704300504 1.1311696182890685
2017 0.6980265112259592 1.5582067956780412
2018 0.8515981827646439 1.1188530300608992
2019 0.7815038538347178 1.2527027241231194

In [35]:
census_regions = {
    
    1: "Connecticut, Maine, Massachusetts, New Hampshire, Rhode Island, Vermont, New Jersey, New York, Pennsylvania",
    2: "Illinois, Indiana, Michigan, Ohio, Wisconsin, Iowa, Kansas, Minnesota, Missouri, Nebraska, North Dakota, South Dakota",
    3: "Delaware, Florida, Georgia, Maryland, North Carolina, South Carolina, Virginia, Washington, District Of Columbia, West Virginia, Alabama, Kentucky, Mississippi, Tennessee, Arkansas, Louisiana, Oklahoma, Texas",
    4: "Arizona, Colorado, Idaho, Montana, Nevada, New Mexico, Utah, Wyoming, Alaska, California, Hawaii, Oregon, Washington"

}
regions_dict = {i: [k.strip() for k in j.split(",")] for i, j in census_regions.items()}
region_data = [ [k, i] for i, j in regions_dict.items() for k in j ]
census_regions_df = pd.DataFrame(columns=["state_name", "region_code"], data= region_data)

In [37]:
epa_region = pd.read_csv("data/states_and_counties.csv")
epa_region = epa_region[['State Name','State Code', "EPA Region"]]
epa_region = epa_region[epa_region['State Code'] != 'CC']
epa_region['State Code'] = epa_region['State Code'].apply(int)
epa_region = epa_region.drop_duplicates(['State Code'], keep='first')

,state_name,region_code,State Name,State Code,EPA Region
0,Connecticut,1,Connecticut,9,1
1,Maine,1,Maine,23,1
2,Massachusetts,1,Massachusetts,25,1
3,New Hampshire,1,New Hampshire,33,1
4,Rhode Island,1,Rhode Island,44,1
5,Vermont,1,Vermont,50,1
6,New Jersey,1,New Jersey,34,2
7,New York,1,New York,36,2
8,Pennsylvania,1,Pennsylvania,42,3
9,Illinois,2,Illinois,17,5
10,Indiana,2,Indiana,18,5
11,Michigan,2,Michigan,26,5
12,Ohio,2,Ohio,39,5
13,Wisconsin,2,Wisconsin,55,5
14,Iowa,2,Iowa,19,7
15,Kansas,2,Kansas,20,7
16,Minnesota,2,Minnesota,27,5
17,Missouri,2,Missouri,29,7
18,Nebraska,2,Nebraska,31,7
19,North Dakota,2,North Dakota,38,8
20,South Dakota,2,South Dakota,46,8
21,Delaware,3,Delaware,10,3
22,Florida,3,Florida,12,4
23,Georgia,3,Georgia,13,4
24,Maryland,3,Maryland,24,3
25,North Carolina,3,North Carolina,37,4
26,South Carolina,3,South Carolina,45,4
27,Virginia,3,Virginia,51,3
28,Washington,3,Washington,53,10
29,District Of Columbia,3,District Of Columbia,11,3
30,West Virginia,3,West Virginia,54,3
31,Alabama,3,Alabama,1,4
32,Kentucky,3,Kentucky,21,4
33,Mississippi,3,Mississippi,28,4
34,Tennessee,3,Tennessee,47,4
35,Arkansas,3,Arkansas,5,6
36,Louisiana,3,Louisiana,22,6
37,Oklahoma,3,Oklahoma,40,6
38,Texas,3,Texas,48,6
39,Arizona,4,Arizona,4,9
40,Colorado,4,Colorado,8,8
41,Idaho,4,Idaho,16,10
42,Montana,4,Montana,30,8
43,Nevada,4,Nevada,32,9
44,New Mexico,4,New Mexico,35,6
45,Utah,4,Utah,49,8
46,Wyoming,4,Wyoming,56,8
47,Alaska,4,Alaska,2,10
48,California,4,California,6,9
49,Hawaii,4,Hawaii,15,9
50,Oregon,4,Oregon,41,10
51,Washington,4,Washington,53,10

In [45]:
# 

census_regions_df.loc[census_regions_df["state_name"]=='California', "region_code"]

4

In [41]:
REGION_LOOKUP = {k:i for i, j in regions_dict.items() for k in j }

In [40]:
REGION_LOOKUP

{1: 'Pennsylvania', 2: 'South Dakota', 3: 'Texas', 4: 'Washington'}