In [1]:
import pandas as pd

In [ ]:
df = pd.read_excel("data/us_census/state_surface_area.xlsx")

In [2]:
from get_population_by_state import GetAgeSex

In [3]:
df = GetAgeSex('2017').read_file_by_population()

In [4]:
df

,STATE,NAME,SEX,POPEST2017_CIV,State and other areas2,surface_area,density
0,0,United States,0,323794924,United States,9147593,35.3967
1,1,Alabama,0,4861465,Alabama,131171,37.062
2,2,Alaska,0,718487,Alaska,1477953,0.486137
3,4,Arizona,0,7025816,Arizona,294207,23.8805
4,5,Arkansas,0,2995637,Arkansas,134771,22.2276
5,6,California,0,39197779,California,403466,97.1526
6,8,Colorado,0,5575734,Colorado,268431,20.7716
7,9,Connecticut,0,3565967,Connecticut,12542,284.322
8,10,Delaware,0,953449,Delaware,5047,188.914
9,11,District of Columbia,0,690589,District of Columbia,158,4370.82
10,12,Florida,0,20895127,Florida,138887,150.447
11,13,Georgia,0,10349084,Georgia,148959,69.4761
12,15,Hawaii,0,1377736,Hawaii,16635,82.8215
13,16,Idaho,0,1714237,Idaho,214045,8.00877
14,17,Illinois,0,12751446,Illinois,143793,88.6792
15,18,Indiana,0,6655353,Indiana,92789,71.7257
16,19,Iowa,0,3140325,Iowa,144669,21.707
17,20,Kansas,0,2886775,Kansas,211754,13.6327
18,21,Kentucky,0,4435540,Kentucky,102269,43.3713
19,22,Louisiana,0,4652908,Louisiana,111898,41.5817
20,23,Maine,0,1333330,Maine,79883,16.691
21,24,Maryland,0,5987619,Maryland,25142,238.152
22,25,Massachusetts,0,6854738,Massachusetts,20202,339.31
23,26,Michigan,0,9969346,Michigan,146435,68.0803
24,27,Minnesota,0,5564223,Minnesota,206232,26.9804
25,28,Mississippi,0,2974699,Mississippi,121531,24.4769
26,29,Missouri,0,6089797,Missouri,178040,34.2047
27,30,Montana,0,1048875,Montana,376962,2.78244
28,31,Nebraska,0,1909278,Nebraska,198974,9.59562
29,32,Nevada,0,2958927,Nevada,284332,10.4066
30,33,New Hampshire,0,1347445,New Hampshire,23187,58.1121
31,34,New Jersey,0,8876105,New Jersey,19047,466.011
32,35,New Mexico,0,2080122,New Mexico,314161,6.6212
33,36,New York,0,19563615,New York,122057,160.283
34,37,North Carolina,0,10168247,North Carolina,125920,80.7516
35,38,North Dakota,0,747731,North Dakota,178711,4.18402
36,39,Ohio,0,11650016,Ohio,105829,110.083
37,40,Oklahoma,0,3912504,Oklahoma,177660,22.0224
38,41,Oregon,0,4141162,Oregon,248608,16.6574
39,42,Pennsylvania,0,12781748,Pennsylvania,115883,110.299
40,44,Rhode Island,0,1051898,Rhode Island,2678,392.792
41,45,South Carolina,0,4982101,South Carolina,77857,63.9904
42,46,South Dakota,0,869387,South Dakota,196350,4.42774
43,47,Tennessee,0,6688806,Tennessee,106798,62.6304
44,48,Texas,0,28179505,Texas,676587,41.6495
45,49,Utah,0,3096332,Utah,212818,14.5492
46,50,Vermont,0,623744,Vermont,23871,26.1298
47,51,Virginia,0,8350328,Virginia,102279,81.6426
48,53,Washington,0,7370914,Washington,172119,42.8245
49,54,West Virginia,0,1815995,West Virginia,62259,29.1684
50,55,Wisconsin,0,5787115,Wisconsin,140268,41.2576
51,56,Wyoming,0,575818,Wyoming,251470,2.28981