In [3]:
import pandas as pd
from constants import *

In [4]:
df = pd.read_excel(TRAP_INCIDENCE)

In [6]:
df[['State', 'AF']]

             State     AF
0              NaN     AF
1          Alabama  0.118
2          Arizona  0.215
3         Arkansas  0.116
4       California  0.253
5         Colorado  0.234
6      Connecticut  0.182
7             D.C.  0.269
8         Delaware   0.16
9          Florida  0.127
10         Georgia  0.145
11           Idaho  0.126
12        Illinois  0.247
13         Indiana  0.181
14            Iowa  0.124
15          Kansas  0.136
16        Kentucky  0.149
17       Louisiana  0.116
18           Maine  0.079
19        Maryland  0.191
20   Massachusetts  0.166
21        Michigan  0.167
22       Minnesota  0.151
23     Mississippi  0.102
24        Missouri   0.12
25         Montana   0.08
26        Nebraska  0.131
27          Nevada  0.199
28   New Hampshire  0.109
29      New Jersey   0.24
30      New Mexico  0.155
31        New York  0.252
32  North Carolina  0.129
33    North Dakota  0.086
34            Ohio  0.171
35        Oklahoma  0.134
36          Oregon  0.139
37    Pennsylvania    0.2
38    Rhode Island  0.158
39  South Carolina   0.11
40    South Dakota  0.076
41       Tennessee  0.155
42           Texas  0.144
43            Utah  0.205
44         Vermont  0.098
45        Virginia  0.172
46      Washington  0.178
47   West Virginia  0.144
48       Wisconsin  0.147
49         Wyoming  0.097

In [13]:
from read_brfss_file import ReadBRFSS
from read_acbs import ReadACBS

In [14]:
brfss, acbs = pd.DataFrame(), pd.DataFrame()
for year in ['2016', '2017', '2018']:
    brfss = brfss.append(ReadBRFSS(year).get_df())
    acbs = acbs.append(ReadACBS(year).get_df())

data/BRFSS/2016/BRFSS_health_data_2016_selected_columns.csv
data/ACBS/2016/ADULT/acbs_2016_adult_public_llcp.sas7bdat
data/BRFSS/2017/BRFSS_health_data_2017_selected_columns.csv
data/ACBS/2017/ADULT/ACBS_2017_ADULT_PUBLIC_LLCP.sas7bdat
data/BRFSS/2018/BRFSS_health_data_2018_selected_columns.csv
data/ACBS/2018/ADULT/acbs_2018_adult_public_llcp.sas7bdat

In [12]:
never_asthma_f = brfss["ASTHMA3"] == 2.0
brfss[never_asthma_f]['_LLCPWT2'].sum()

658595609.3568088

In [24]:
valid_age = (acbs['AGEDX'] != 777) | (acbs['AGEDX'] != 999)
last_12_months = acbs['INCIDNT'] == 1
df2_valid_age = acbs[valid_age]
# df2_valid_age[last_12_months]['LLCPWT_F'].sum()

df2_valid_age[last_12_months].groupby(['_state'])['LLCPWT_F'].sum().reset_index()

    _state       LLCPWT_F
0      4.0   40520.541776
1      6.0  189526.034386
2      9.0   29564.060711
3     12.0  140597.035349
4     13.0  115461.306580
5     15.0    7790.003303
6     17.0   57974.926877
7     18.0   46295.124375
8     19.0   14606.478792
9     20.0   16358.097517
10    21.0   20157.463854
11    23.0   10435.441620
12    24.0   33720.367283
13    25.0   33918.365104
14    26.0   61364.779449
15    27.0   25292.392578
16    29.0   21505.132294
17    30.0    3721.488866
18    31.0   11171.686064
19    32.0   12461.263383
20    33.0    6242.758910
21    34.0   35586.179531
22    35.0   11406.353076
23    36.0  161158.617343
24    39.0  157608.815540
25    40.0   11504.641511
26    41.0   33400.161040
27    42.0   99230.485362
28    44.0    8445.918158
29    48.0  109835.490190
30    49.0    7966.955039
31    50.0    4988.710842
32    55.0   31579.697859
33    72.0   26327.423593

In [23]:
never_asthma_f = brfss["ASTHMA3"] == 2.0
never_asthma_df = brfss[never_asthma_f]
never_asthma_df = never_asthma_df.groupby(['_STATE'])['_LLCPWT2'].sum().reset_index()
never_asthma_df['count'] = never_asthma_df['_LLCPWT2']

    _STATE      _LLCPWT2
0      1.0  9.611477e+06
1      2.0  1.431259e+06
2      4.0  1.366373e+07
3      5.0  5.876964e+06
4      6.0  7.813173e+07
5      8.0  1.130017e+07
6      9.0  7.216009e+06
7     10.0  1.964919e+06
8     11.0  1.437580e+06
9     12.0  4.437335e+07
10    13.0  2.082959e+07
11    15.0  2.808336e+06
12    16.0  3.319195e+06
13    17.0  2.563917e+07
14    18.0  1.306865e+07
15    19.0  6.398424e+06
16    20.0  5.709643e+06
17    21.0  8.727066e+06
18    22.0  9.263195e+06
19    23.0  2.727542e+06
20    24.0  1.210528e+07
21    25.0  1.390136e+07
22    26.0  1.964330e+07
23    27.0  1.143380e+07
24    28.0  5.897539e+06
25    29.0  1.219952e+07
26    30.0  2.140958e+06
27    31.0  3.812539e+06
28    32.0  6.068110e+06
29    33.0  2.720030e+06
30    34.0  1.849607e+07
31    35.0  4.034176e+06
32    36.0  4.019517e+07
33    37.0  2.081651e+07
34    38.0  1.546976e+06
35    39.0  2.354395e+07
36    40.0  7.624219e+06
37    41.0  8.145993e+06
38    42.0  2.591945e+07
39    44.0  2.124260e+06
40    45.0  1.018289e+07
41    46.0  1.765799e+06
42    47.0  1.321775e+07
43    48.0  5.507588e+07
44    49.0  5.631186e+06
45    50.0  1.270152e+06
46    51.0  1.718755e+07
47    53.0  1.459800e+07
48    54.0  3.611883e+06
49    55.0  1.187350e+07
50    56.0  1.167059e+06
51    66.0  2.855367e+05
52    72.0  6.788731e+06
53    78.0  7.249709e+04

In [ ]:
lifetime_asthma_ques = self.brfss.groupby(['_STATE', 'ASTHMA3'])['ASTHMA3'].agg(['count']).reset_index()
never_asthma = lifetime_asthma_ques["ASTHMA3"] == 2.0
never_asthma_df = lifetime_asthma_ques[never_asthma]