In [23]:
import pandas as pd
from constants import *

In [5]:
fname = "data/ev_sales_2019_evadoption.xlsx"
df = pd.read_excel(fname)

In [12]:
df = df[['State', 'EV (BEV + PHEV) Sales']]

In [13]:
epa_region = pd.read_csv("data/states_and_counties.csv")
epa_region = epa_region[['State Name','State Code', "EPA Region"]]
epa_region = epa_region[epa_region['State Code'] != 'CC']
epa_region['State Code'] = epa_region['State Code'].apply(int)
epa_region = epa_region.drop_duplicates(['State Code'], keep='first')
mdf = df.merge(epa_region, left_on="State", right_on="State Name", how='left')

In [14]:
mdf

,State,EV (BEV + PHEV) Sales,State Name,State Code,EPA Region
0,Alabama,1007,Alabama,1.0,4.0
1,Alaska,143,Alaska,2.0,10.0
2,Arizona,7591,Arizona,4.0,9.0
3,Arkansas,538,Arkansas,5.0,6.0
4,California,145020,California,6.0,9.0
5,Colorado,9007,Colorado,8.0,8.0
6,Connecticut,3310,Connecticut,9.0,1.0
7,Delaware,822,Delaware,10.0,3.0
8,District of Columbia,1015,NaN,NaN,NaN
9,Florida,15794,Florida,12.0,4.0
10,Georgia,5138,Georgia,13.0,4.0
11,Hawaii,3117,Hawaii,15.0,9.0
12,Idaho,538,Idaho,16.0,10.0
13,Illinois,7630,Illinois,17.0,5.0
14,Indiana,2207,Indiana,18.0,5.0
15,Iowa,753,Iowa,19.0,7.0
16,Kansas,847,Kansas,20.0,7.0
17,Kentucky,804,Kentucky,21.0,4.0
18,Louisiana,720,Louisiana,22.0,6.0
19,Maine,989,Maine,23.0,1.0
20,Maryland,6806,Maryland,24.0,3.0
21,Massachusetts,7858,Massachusetts,25.0,1.0
22,Michigan,1830,Michigan,26.0,5.0
23,Minnesota,3640,Minnesota,27.0,5.0
24,Mississippi,273,Mississippi,28.0,4.0
25,Missouri,2053,Missouri,29.0,7.0
26,Montana,318,Montana,30.0,8.0
27,Nebraska,516,Nebraska,31.0,7.0
28,Nevada,3227,Nevada,32.0,9.0
29,New Hampshire,1030,New Hampshire,33.0,1.0
30,New Jersey,9433,New Jersey,34.0,2.0
31,New Mexico,787,New Mexico,35.0,6.0
32,New York,14823,New York,36.0,2.0
33,North Carolina,5393,North Carolina,37.0,4.0
34,North Dakota,114,North Dakota,38.0,8.0
35,Ohio,5903,Ohio,39.0,5.0
36,Oklahoma,774,Oklahoma,40.0,6.0
37,Oregon,7063,Oregon,41.0,10.0
38,Pennsylvania,6354,Pennsylvania,42.0,3.0
39,Rhode Island,682,Rhode Island,44.0,1.0
40,South Carolina,1335,South Carolina,45.0,4.0
41,South Dakota,186,South Dakota,46.0,8.0
42,Tennessee,2122,Tennessee,47.0,4.0
43,Texas,5780,Texas,48.0,6.0
44,Utah,3029,Utah,49.0,8.0
45,Vermont,1005,Vermont,50.0,1.0
46,Virginia,7014,Virginia,51.0,3.0
47,Washington,12172,Washington,53.0,10.0
48,West Virginia,250,West Virginia,54.0,3.0
49,Wisconsin,1962,Wisconsin,55.0,5.0
50,Wyoming,144,Wyoming,56.0,8.0
51,Total US,320866,NaN,NaN,NaN

In [20]:
total_us_ev_sales = mdf[mdf['State'] == 'Total US']['EV (BEV + PHEV) Sales'].tolist()[0]
mdf['us_percent'] = (mdf['EV (BEV + PHEV) Sales']*100)/total_us_ev_sales

In [21]:
mdf

,State,EV (BEV + PHEV) Sales,State Name,State Code,EPA Region,us_percent
0,Alabama,1007,Alabama,1.0,4.0,0.313838
1,Alaska,143,Alaska,2.0,10.0,0.044567
2,Arizona,7591,Arizona,4.0,9.0,2.365785
3,Arkansas,538,Arkansas,5.0,6.0,0.167671
4,California,145020,California,6.0,9.0,45.196437
5,Colorado,9007,Colorado,8.0,8.0,2.807091
6,Connecticut,3310,Connecticut,9.0,1.0,1.031583
7,Delaware,822,Delaware,10.0,3.0,0.256182
8,District of Columbia,1015,NaN,NaN,NaN,0.316331
9,Florida,15794,Florida,12.0,4.0,4.922304
10,Georgia,5138,Georgia,13.0,4.0,1.601292
11,Hawaii,3117,Hawaii,15.0,9.0,0.971434
12,Idaho,538,Idaho,16.0,10.0,0.167671
13,Illinois,7630,Illinois,17.0,5.0,2.377940
14,Indiana,2207,Indiana,18.0,5.0,0.687826
15,Iowa,753,Iowa,19.0,7.0,0.234677
16,Kansas,847,Kansas,20.0,7.0,0.263973
17,Kentucky,804,Kentucky,21.0,4.0,0.250572
18,Louisiana,720,Louisiana,22.0,6.0,0.224393
19,Maine,989,Maine,23.0,1.0,0.308228
20,Maryland,6806,Maryland,24.0,3.0,2.121135
21,Massachusetts,7858,Massachusetts,25.0,1.0,2.448997
22,Michigan,1830,Michigan,26.0,5.0,0.570332
23,Minnesota,3640,Minnesota,27.0,5.0,1.134430
24,Mississippi,273,Mississippi,28.0,4.0,0.085082
25,Missouri,2053,Missouri,29.0,7.0,0.639831
26,Montana,318,Montana,30.0,8.0,0.099107
27,Nebraska,516,Nebraska,31.0,7.0,0.160815
28,Nevada,3227,Nevada,32.0,9.0,1.005716
29,New Hampshire,1030,New Hampshire,33.0,1.0,0.321006
30,New Jersey,9433,New Jersey,34.0,2.0,2.939857
31,New Mexico,787,New Mexico,35.0,6.0,0.245274
32,New York,14823,New York,36.0,2.0,4.619685
33,North Carolina,5393,North Carolina,37.0,4.0,1.680764
34,North Dakota,114,North Dakota,38.0,8.0,0.035529
35,Ohio,5903,Ohio,39.0,5.0,1.839709
36,Oklahoma,774,Oklahoma,40.0,6.0,0.241222
37,Oregon,7063,Oregon,41.0,10.0,2.201230
38,Pennsylvania,6354,Pennsylvania,42.0,3.0,1.980266
39,Rhode Island,682,Rhode Island,44.0,1.0,0.212550
40,South Carolina,1335,South Carolina,45.0,4.0,0.416062
41,South Dakota,186,South Dakota,46.0,8.0,0.057968
42,Tennessee,2122,Tennessee,47.0,4.0,0.661335
43,Texas,5780,Texas,48.0,6.0,1.801375
44,Utah,3029,Utah,49.0,8.0,0.944008
45,Vermont,1005,Vermont,50.0,1.0,0.313215
46,Virginia,7014,Virginia,51.0,3.0,2.185959
47,Washington,12172,Washington,53.0,10.0,3.793484
48,West Virginia,250,West Virginia,54.0,3.0,0.077914
49,Wisconsin,1962,Wisconsin,55.0,5.0,0.611470
50,Wyoming,144,Wyoming,56.0,8.0,0.044879
51,Total US,320866,NaN,NaN,NaN,100.000000

In [30]:
mdf = mdf[~mdf['State Code'].isin(EXCLUDE_STATES)]
mdf_carb = mdf[mdf['State Code'].isin(CARB)]
mdf_noncarb = mdf[~mdf['State Code'].isin(CARB)]
mdf_noncarb = mdf_noncarb[mdf_noncarb['State']!='Total US']

In [31]:
mdf_carb['us_percent'].sum(), mdf_noncarb['us_percent'].sum()

(64.20000872638423, 29.770059775731923)

In [32]:
mdf_carb

,State,EV (BEV + PHEV) Sales,State Name,State Code,EPA Region,us_percent
4,California,145020,California,6.0,9.0,45.196437
5,Colorado,9007,Colorado,8.0,8.0,2.807091
6,Connecticut,3310,Connecticut,9.0,1.0,1.031583
19,Maine,989,Maine,23.0,1.0,0.308228
20,Maryland,6806,Maryland,24.0,3.0,2.121135
21,Massachusetts,7858,Massachusetts,25.0,1.0,2.448997
30,New Jersey,9433,New Jersey,34.0,2.0,2.939857
32,New York,14823,New York,36.0,2.0,4.619685
37,Oregon,7063,Oregon,41.0,10.0,2.201230
39,Rhode Island,682,Rhode Island,44.0,1.0,0.212550
45,Vermont,1005,Vermont,50.0,1.0,0.313215

In [34]:
epa_region[epa_region['State Code'].isin(EXCLUDE_STATES)]

                State Name  State Code  EPA Region
322               Delaware          10           3
325   District Of Columbia          11           3
2254          Pennsylvania          42           3
2966            Washington          53          10

In [37]:
epa_region[epa_region['State Name'] == 'Minnesota']

     State Name  State Code  EPA Region
1322  Minnesota          27           5